apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: depl1
  name: depl1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depl1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: depl1
    spec:
      containers:
      - image: busybox:stable
        name: busybox
        resources: {}
status: {}
