apiVersion: v1
kind: Pod
metadata
spec:
  containers:
    - name: cmd-demo-container
      image: busybox:stable
      command: ["printenv"]
      args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure